In [12]:
import numpy as np
import pandas as pd

# 주피터 노트북의 출력을 소숫점 3자리까지로 제한 
%precision 3

'%.3f'

In [9]:
df = pd.read_csv('../stat_anlysis/data/ch2_scores_em.csv', 
                 index_col = 'student number') 
df.head()
# csv는 단순 row 파일(단순 데이터파일) -> 이 데이터를 pd라는 객체에 넣어서 df에 저장 -> df의 앞 5행까지 출력 

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [16]:
scores = np.array(df['english'])[:10] #np에서 english 열의 10개의 요소를 가진 scroes 배열을 생성
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [22]:
scores_df = pd.DataFrame({'scores': scores},
                         index = pd.Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
                                          name = 'student'))
scores_df

scores
student        
A            42
B            69
C            56
D            41
E            57
F            48
G            65
H            49
I            65
J            58

In [23]:
sum(scores) /len(scores)

55.000

In [24]:
np.mean(scores)

55.000

In [25]:
scores_df.mean()

scores    55.0
dtype: float64

In [26]:
# 1.1.2 중앙값 - 시험

sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [31]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2 - 1]
    m1 = sorted_scores[n//2]
    median = (m0+m1) /2
else:
    median = sorted_scores[(n+1)//2 -1]
median

56.500

In [33]:
pd.Series([1, 1, 1, 2, 2, 3]).mode()

0    1
dtype: int64

In [34]:
pd.Series([1, 2, 3, 4, 5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [47]:
# 산포도에서 사용하는 지표가 분산, 표준편차(동그라미)
# 산포도로 평균을 내는 것은 부적절하다. 


mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [48]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52,59]
another_mean = np.mean(scores)
another_deviation = another_scores - another_mean
another_deviation

# 편차를 비교할 때 편차의 평균이 0이 나올 때도 있다(별표) 산포도를 구할때는 편차만을 이용하는 건 부적절 

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [49]:
np.mean(deviation)

0.000

In [51]:
np.mean(another_deviation)

0.000

In [53]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

scores  deviation
student                   
A            42      -13.0
B            69       14.0
C            56        1.0
D            41      -14.0
E            57        2.0
F            48       -7.0
G            65       10.0
H            49       -6.0
I            65       10.0
J            58        3.0

In [56]:
# 산포도의 지표로 편차를 사용하는 건 바람직하지만, 편차의 제곱을 아용해서 분산정도를 상쇄시키지 않게 한다. 이렇게 사용하는 것을 분산(별표)라고 한다.

np.mean(deviation **2)

86.000

In [59]:
np.var(scores)

86.000

In [60]:
scores_df.var()

scores    95.555556
dtype: float64

In [62]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

scores  deviation  square of deviation
student                                        
A            42      -13.0                169.0
B            69       14.0                196.0
C            56        1.0                  1.0
D            41      -14.0                196.0
E            57        2.0                  4.0
F            48       -7.0                 49.0
G            65       10.0                100.0
H            49       -6.0                 36.0
I            65       10.0                100.0
J            58        3.0                  9.0

In [63]:
summary_df.mean()

scores                 55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [65]:
# 분산에 제곱근을 취한 것이 표준편차(시험) 

a = np.mean(deviation **2)
np.sqrt(a)


9.274

In [66]:
np.sqrt(np.var(scores, ddof=0))


9.274

In [69]:
np.std(scores, ddof=0)

9.274

In [70]:
# 평균을 중심으로 +- 표준편차한 구간을 1시그마 구간이라한다. 표준편차를 2배로 하면 2시그마... 

np.max(scores) - np.min(scores)

np.int64(28)

In [73]:
# 사분위 범위(별표), 27p 그림은 외우기 시험 나옴 빈칸에 글자 쓰기 
# 각 25, 50, 75, 100 구간을 Q1~ Q4구간이라고 함

scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.000

In [75]:
pd.Series(scores).describe()

count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64

In [77]:
# z 점수(별표- 시험문제)

z = (scores - np.mean(scores)) / np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [79]:
# 편찻값 = 졍규화한 값(밑줄)

z1 = 50 + 10*z
z1

array([35.982, 65.097, 51.078, 34.903, 52.157, 42.452, 60.783, 43.53 ,
       60.783, 53.235])

In [81]:
scores_df['deviation value'] = z1
scores_df


scores  deviation value
student                         
A            42        35.981739
B            69        65.096588
C            56        51.078328
D            41        34.903412
E            57        52.156655
F            48        42.451706
G            65        60.783277
H            49        43.530034
I            65        60.783277
J            58        53.234983

In [83]:
english_scores = np.array(df['english'])
pd.Series(english_scores).describe()

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [101]:
freq,_ = np.histogram(english_scores, bins=10, range=(0, 100))
freq

freq_class = [f'{i}~{i+10}' for i in range(0, 100, 10)]
freq_dist_df =pd.DataFrame({'frequency':freq},
                           index = pd.Index(freq_class,
                                            name = 'class'))

freq_dist_df

frequency
class            
0~10            0
10~20           0
20~30           0
30~40           2
40~50           8
50~60          16
60~70          18
70~80           6
80~90           0
90~100          0

In [97]:
class_value = [(i+(i+10))//2 for i in range(0, 100, 10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [91]:
# 상대도수: 전체 데이터에서 해당 계급의 데이터가 차지하는 비율(밑줄)

rel_freq = freq / freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [93]:
cm_rel_freq = np.cumsum(rel_freq)
cm_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [102]:
freq_dist_df['class value'] = class_value
freq_dist_df['relative frequency'] = rel_freq
freq_dist_df['cumlative relative frequency'] = cm_rel_freq
freq_dist_df = freq_dist_df[['class value', 'frequency','relative frequency', 'cumlative relative frequency']]

freq_dist_df

class value  frequency  relative frequency  \
class                                                
0~10              5          0                0.00   
10~20            15          0                0.00   
20~30            25          0                0.00   
30~40            35          2                0.04   
40~50            45          8                0.16   
50~60            55         16                0.32   
60~70            65         18                0.36   
70~80            75          6                0.12   
80~90            85          0                0.00   
90~100           95          0                0.00   

        cumlative relative frequency  
class                                 
0~10                            0.00  
10~20                           0.00  
20~30                           0.00  
30~40                           0.04  
40~50                           0.20  
50~60                           0.52  
60~70                           0.88  
70~80                           1.00  
80~90                           1.00  
90~100                          1.00

In [ ]:
# 46이미지를 만드는 것이 목표 42- 46까지 코드 작성 


